In [1]:
# importing libraries
import pandas as pd
import matplotlib.pyplot as plt 
import sklearn
from sklearn.model_selection import train_test_split
import numpy as np
%matplotlib inline

In [2]:
cols = [
    "area",
    "perimeter",
    "compactness",
    "kernel_length",
    "kernel_width",
    "asymmetry_coefficient",
    "kernel_groove_length",
    "label"
]

df = pd.read_csv(
    "seeds_dataset.tsv",
    sep=r"\s+",
    header=None,
    names=cols
)

df.head(10)

,area,perimeter,compactness,kernel_length,kernel_width,asymmetry_coefficient,kernel_groove_length,label
0,15.26,14.84,0.8710,5.763,3.312,2.221,5.220,1
1,14.88,14.57,0.8811,5.554,3.333,1.018,4.956,1
2,14.29,14.09,0.9050,5.291,3.337,2.699,4.825,1
3,13.84,13.94,0.8955,5.324,3.379,2.259,4.805,1
4,16.14,14.99,0.9034,5.658,3.562,1.355,5.175,1
5,14.38,14.21,0.8951,5.386,3.312,2.462,4.956,1
6,14.69,14.49,0.8799,5.563,3.259,3.586,5.219,1
7,14.11,14.10,0.8911,5.420,3.302,2.700,5.000,1
8,16.63,15.46,0.8747,6.053,3.465,2.040,5.877,1
9,16.44,15.25,0.8880,5.884,3.505,1.969,5.533,1

In [ ]:
# Basic information about the dataset
print("\nDataset Shape:", df.shape)
print("Column Names:", df.columns.tolist())
print("Data Types:\n", df.dtypes)

Dataset Shape: (210, 8)
Column Names: ['area', 'perimeter', 'compactness', 'kernel_length', 'kernel_width', 'asymmetry_coefficient', 'kernel_groove_length', 'label']
Data Types:
 area                     float64
perimeter                float64
compactness              float64
kernel_length            float64
kernel_width             float64
asymmetry_coefficient    float64
kernel_groove_length     float64
label                      int64
dtype: object

In [5]:
#summary statistics
print("\nSummary Statistics:\n" )
df.describe()

Summary Statistics:

,area,perimeter,compactness,kernel_length,kernel_width,asymmetry_coefficient,kernel_groove_length,label
count,210.000000,210.000000,210.000000,210.000000,210.000000,210.000000,210.000000,210.000000
mean,14.847524,14.559286,0.870999,5.628533,3.258605,3.700201,5.408071,2.000000
std,2.909699,1.305959,0.023629,0.443063,0.377714,1.503557,0.491480,0.818448
min,10.590000,12.410000,0.808100,4.899000,2.630000,0.765100,4.519000,1.000000
25%,12.270000,13.450000,0.856900,5.262250,2.944000,2.561500,5.045000,1.000000
50%,14.355000,14.320000,0.873450,5.523500,3.237000,3.599000,5.223000,2.000000
75%,17.305000,15.715000,0.887775,5.979750,3.561750,4.768750,5.877000,3.000000
max,21.180000,17.250000,0.918300,6.675000,4.033000,8.456000,6.550000,3.000000

In [6]:
# ⁠Generate descriptive statistics table (mean, std, min, max, quartiles) — per feature and per class
df.groupby('label').describe()

       area                                                               \
      count       mean       std    min      25%     50%      75%    max
label
1      70.0  14.334429  1.215704  11.23  13.7500  14.355  15.0450  17.08
2      70.0  18.334286  1.439496  15.38  17.3300  18.720  19.1375  21.18
3      70.0  11.873857  0.723004  10.59  11.2625  11.835  12.4250  13.37

      perimeter             ... asymmetry_coefficient         \
          count       mean  ...                   75%    max
label                       ...
1          70.0  14.294286  ...               3.30100  6.685
2          70.0  16.135714  ...               4.43600  6.682
3          70.0  13.247857  ...               5.46725  8.456

      kernel_groove_length                                             \
                     count      mean       std    min     25%     50%
label
1                     70.0  5.087214  0.263699  4.519  4.9245  5.0940
2                     70.0  6.020600  0.253934  5.144  5.8775  5.9815
3                     70.0  5.116400  0.162068  4.745  5.0020  5.0915


           75%    max
label
1      5.22350  5.877
2      6.18775  6.550
3      5.22850  5.491

[3 rows x 56 columns]

##### There are exactly 70 samples for each variety. This balance is ideal for training classification models as it prevents the model from developing a bias toward a majority class.

In [7]:

# Checking for missing values and duplicates
missing_values = df.isnull().sum()
duplicates = df.duplicated().sum()
print("\nMissing values per column:\n", missing_values)
print("Number of duplicate rows:", duplicates)

Missing values per column:
 area                     0
perimeter                0
compactness              0
kernel_length            0
kernel_width             0
asymmetry_coefficient    0
kernel_groove_length     0
label                    0
dtype: int64
Number of duplicate rows: 0

##### There are no missing values and dublicate rows in this dataset .